//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "access_keys")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub pid: Uuid,
    #[sea_orm(unique)]
    pub access_key_id: String,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub secret_encrypted: Vec<u8>,
    pub label: String,
    pub status: String,
    pub expires_at: Option<DateTimeWithTimeZone>,
    pub user_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::access_key_permissions::Entity")]
    AccessKeyPermissions,
    #[sea_orm(has_many = "super::access_key_prefixes::Entity")]
    AccessKeyPrefixes,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::access_key_permissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccessKeyPermissions.def()
    }
}

impl Related<super::access_key_prefixes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccessKeyPrefixes.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}
