//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "access_key_permissions")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "idx_akp_key_action")]
    pub action: String,
    #[sea_orm(unique_key = "idx_akp_key_action")]
    pub access_key_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::access_keys::Entity",
        from = "Column::AccessKeyId",
        to = "super::access_keys::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    AccessKeys,
}

impl Related<super::access_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccessKeys.def()
    }
}
