//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "audit_logs")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub pid: Uuid,
    pub occurred_at: DateTimeWithTimeZone,
    pub user_id: Option<i32>,
    pub access_key_id: Option<String>,
    pub bucket_id: Option<i32>,
    pub object_key: Option<String>,
    pub action: String,
    pub outcome: String,
    pub status_code: i32,
    pub bytes: i64,
    pub duration_ms: i32,
    pub request_id: String,
    pub ip: String,
    pub user_agent: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
