//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "multipart_uploads")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub pid: Uuid,
    pub object_key: String,
    pub upstream_upload_id: String,
    pub reserved_bytes: i64,
    pub bucket_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::buckets::Entity",
        from = "Column::BucketId",
        to = "super::buckets::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Buckets,
}

impl Related<super::buckets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Buckets.def()
    }
}
