//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub pid: Uuid,
    #[sea_orm(unique)]
    pub email: String,
    pub password: String,
    #[sea_orm(unique)]
    pub api_key: String,
    pub name: String,
    pub role: String,
    pub max_bytes: i64,
    pub used_bytes: i64,
    pub reserved_bytes: i64,
    pub must_change_password: bool,
    pub api_key_prefix: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::access_keys::Entity")]
    AccessKeys,
    #[sea_orm(has_many = "super::buckets::Entity")]
    Buckets,
}

impl Related<super::access_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccessKeys.def()
    }
}

impl Related<super::buckets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Buckets.def()
    }
}
